// shared/types.ts
import * as Y from 'yjs';

// Define the Snippet interface
export interface Snippet {
  _id?: string; // MongoDB's ObjectID (optional, as it's generated by the database)
  content: Y.Doc;
  token: string;
  canEdit: boolean;
  createdAt: Date;
  expiresAt?: Date;
}
